config/routes.rb
Rails.application.routes.draw do
  # get 'carts/show'
  #
  # get 'carts/add'
  #
  # get 'carts/remove'

  resources :products, only: [:show, :index]
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  ActiveAdmin.routes(self)
  resources :profiles
end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id                 :integer          not null, primary key
#  photo_file_name    :string
#  photo_content_type :string
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  product_id         :integer
#

class Picture < ActiveRecord::Base
  belongs_to :product
  has_attached_file :photo
  validates_attachment :photo, content_type: { content_type:     ["image/jpg", "image/jpeg", "image/png"] }
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                         :integer          not null, primary key
#  title                      :string
#  description                :text
#  price                      :float
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  thumbnail_img_file_name    :string
#  thumbnail_img_content_type :string
#  thumbnail_img_file_size    :integer
#  thumbnail_img_updated_at   :datetime
#  cover_img_file_name        :string
#  cover_img_content_type     :string
#  cover_img_file_size        :integer
#  cover_img_updated_at       :datetime
#  ptype                      :string
#  slug                       :string
#  size                       :integer          default(0)
#  color                      :string
#

class Product < ActiveRecord::Base
  has_attached_file :thumbnail_img, :styles => { :medium => "364x503>", :thumb => "100x100>" }
  has_attached_file :cover_img, :styles => { :large => "1024x768>", :medium => "640x320>" }
  validates_attachment :thumbnail_img, content_type: { content_type:     ["image/jpg", "image/jpeg", "image/png"] }
  validates_attachment :cover_img, content_type: { content_type:     ["image/jpg", "image/jpeg", "image/png"] }

  has_many :pictures
  accepts_nested_attributes_for :pictures, allow_destroy: true

  validates :ptype, inclusion: { in: %w(belts handbags shoes accessories clothing bestselling collections) }

  extend FriendlyId
  friendly_id :title, use: :slugged

  enum size: { "medium" => 0, "large" => 1, "xlarge" => 2, "small" => 3, "one-size" => 4, "handbags" => 5}

  def cart_action(current_user_id)
    if $redis.sismember "cart#{current_user_id}", id
      "Remove from"
    else
      "Add to"
    end
  end
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :integer          not null, primary key
#  address    :string
#  user_name  :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#

class Profile < ActiveRecord::Base
  belongs_to :user
  extend FriendlyId
  friendly_id :user_name, use: :slugged
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :products

  after_create :create_profile

  def create_profile
    self.build_profile.save!
  end

  def cart_count
    $redis.scard "cart#{id}"
  end

  def cart_total_price
    total_price = 0
    get_cart_product.each { |movie| total_price += product.price }
    total_price
  end

  def get_cart_product
    cart_ids = $redis.smembers "cart#{id}"
    Product.find(cart_ids)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  def show
    cart_ids = $redis.smembers current_user_cart
    @cart_products = Product.find(cart_ids)
  end

  def add
    $redis.sadd current_user_cart, params[:product_id], params[:size]
    render json: current_user.cart_count, status: 200
  end

  def remove
    $redis.srem current_user_cart, params[:product_id], params[:size]
    render json: current_user.cart_count, status: 200
  end

  private

    def current_user_cart
      "cart#{current_user.id}"
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:type]
      @products = Product.where(ptype: params[:type])
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.friendly.find(params[:id])
    @cart_action = @product.cart_action current_user.try :id
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]

  def edit
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to edit_profile_path, notice: 'Your profile was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:address, :user_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/carts/show.html.erb
<!-- <h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p> -->

<section class="text-center">
  <div class="container-fluid h-space-in-all-large">
    <div class="row">
      <div class='col-xs-6'>
        <table class='table table-bordered'>
          <thead>
            <tr>
              <th class='text-center'>Title</th>
              <th class='text-center'>Price</th>
            </tr>
          </thead>
          <tbody>
            <% @cart_products.each do |p| %>
              <tr>
                <td><%= p.title %></td>
                <td><%= p.price %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div> <!-- /.row -->
    <%= link_to "Checkout", '', class: "button" unless current_user.get_cart_product.blank? %>
  </div>
</sestion>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lachitus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="header">

    <div class="navbar lachitus-navbar lachitus-navbar__head spacer-none -bg-gold" role="navigation">
      <ul class="nav nav-pills pull-right">
        <li>
          <form class="form-inline">
            <div class="form-group pull-left">
              <div class="input-group">
                <input type="text" class="form-control -border-color-gold" id="exampleInputAmount" placeholder="Search">
              </div>
            </div>
            <button type="submit" class="btn btn__search"><i class="fa fa-search"></i></button>
          </form>
        </li>
        <!-- <li><a href="/"><i class="fa fa-shopping-cart fa-2x"></i> Cart (<span class="cart-count"></span>)</a></li> -->

        <% if user_signed_in? %>
          <li>
            <%= link_to cart_path do%>
              <i class="fa fa-shopping-cart fa-2x"></i> Cart (<span class="cart-count"><%=current_user.cart_count%></span>)
            <%end%>
          </li>
          <li><a href="/profiles/<%= current_user.profile.slug %>/edit"><i class="fa fa-user fa-2x"></i> Edit profile</a></li>
           |
          <li><a href="/users/sign_out" data-method="delete"><i class="fa fa-sign-out fa-2x"></i> Sign-Out</a></li>
        <% else %>
          <li><a href="/users/sign_in"><i class="fa fa-sign-in fa-2x"></i> Sign-In</a></li>
        <% end %>
      </ul>
    </div>
  </header>

  <main>
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>
    <%= yield %>
  </main>

  <footer class="footer -bg-dark text-center">
    <div class="container">
      <ul class="nav navbar-nav footer__navbar-nav">
        <li>
          <a href="/term-condition" target="_blank" class="text-captilizer"> Term & condition</a>
        </li>
        <li>
          <a href="/size-guide" target="_blank" class="text-captilizer"> Size guide</a>
        </li>
        <li>
          <a href="/about" target="_blank" class="text-captilizer"> About us</a>
        </li>
      </ul>
    </div>
    <div class="container">
      <p><span class="glyphicon glyphicon-heart"></span> 	&#169; Copyright 2015 - Lochitus INC</p>
    </div>
  </footer>

</body>
</html>

app/views/pages/_section_header_bar.html.erb
<section>
  <div class="header-bg wrap-content">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#js-lachitus-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <h1>
      <a href="/" class="logo"></a>
    </h1>
  </div>

  <div class="navbar lachitus-navbar spacer-none" role="navigation">

    <nav class="collapse -bg-gold navbar-collapse" id="js-lachitus-collapse">
      <ul class="nav h-text-md-center nav__main text-uppercase">
        <li><a class="nav" href="/products?type=collections">New Collections</a></li>
        <li><a class="nav" href="/products?type=clothing">Clothing</a></li>
        <li><a class="nav" href="/products?type=handbags">Handbags</a></li>
        <li><a class="nav" href="/products?type=shoes">Shoes</a></li>
        <li><a class="nav" href="/products?type=jewelry">Jewelry</a></li>
        <li><a class="nav" href="/products?type=accessories">Accessories</a></li>
      </ul>
    </nav>

  </div>
</section>

app/views/pages/about.html.erb
<%= render partial: "pages/section_header_bar" %>

<section class="wrap-content section-about section-about-lachitus">
  <div class="container">
    <div class="profile-container">
      <div class="section-box">
        <div class="profile-text">
          <p class="text-center -color-gold"><big>
            About Us
          </big></p>
          <p><small>
            LACHITUS is a fashion business that was establised from the desire of its founder, Ms.

            Chi Tran. Because of her young-age hope  about being well-dressed, high class, and

            impressive, she dreamed that she would not only help herself in style but also people all

            over the world. And that is why she decided to open up a fashion business based on its

            motto "beautiful for me, beautiful for everybody." With such inspiration, our company

            always chooses and creates high aesthetic products that give the wearer a sense of

            glamour, luxury, high class like many famous stars around the world.
          </small></p>

          <p><small>
            Another advantage of the LACHITUS fashion products is that customers don't need to

            spend a lot of money to own these beautiful and luxurious outfits. Our company wants

            to help people of all ages and social classes to be able to dress nicely, impressively, and

            modernly like their dream with only affordable prices.
          </small></p>
        </div>
        <div class="profile-social -bg-gold text-center">

          <ul class="nav navbar-nav social">
            <li>
              <a class="ripple-centered" href="https://www.facebook.com" target="_blank"><i class="fa fa-3x fa-facebook"></i></a>
            </li>
            <li>
              <a class="ripple-centered" href="https://twitter.com/" target="_blank"><i class="fa fa-3x fa-twitter"></i></a>
            </li>
            <li>
              <a class="ripple-centered" href="https://www.linkedin.com/" target="_blank"><i class="fa fa-3x fa-linkedin"></i></a>
            </li>
            <li>
              <a class="ripple-centered" href="https://plus.google.com" target="_blank"><i class="fa fa-3x fa-google-plus"></i></a>
            </li>
            <li>
              <a class="ripple-centered" href="https://www.instagram.com/" target="_blank"><i class="fa fa-3x fa-instagram"></i></a>
            </li>
          </ul>

        </div>
      </div>
      <div class="profile-text">
        <p class="text-center -color-gold"><big>
          Foundation
        </big></p>
        <p><small>
          Established since 2015, the basis of brand LACHITUS is a philanthropic organization that

          helps people with hard life circumstances such as no home, no food to eat, and no

          clothes to wear. Besides, we encourage them to move on in life and pursue their

          dreams. All these charity activities  are planned and performed every year by financial

          resources of sold Lachitus products. We always hoped that everyone can have a chance

          to live a wonderful life: good food, stable house, and beautiful clothes.
        </small></p>
      </div>
    </div>
  </div>
</section> <!-- About Chi -->

app/views/pages/home.html.erb
<section id="lachitus-slide" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#lachitus-slide" data-slide-to="0" class="active"></li>
    <li data-target="#lachitus-slide" data-slide-to="1"></li>
    <li data-target="#lachitus-slide" data-slide-to="2"></li>
    <li data-target="#lachitus-slide" data-slide-to="3"></li>
    <li data-target="#lachitus-slide" data-slide-to="4"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("lachitus-slide1.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("lachitus-slide2.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("lachitus-slide3.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("lachitus-slide4.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("lachitus-slide5.jpg") %>
    </div>
  </div>
</section> <!--/.slider -->

<section>
  <div class="header-bg wrap-content">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#js-lachitus-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <h1>
      <a href="/" class="logo"></a>
    </h1>
  </div>

  <div class="navbar lachitus-navbar spacer-none" role="navigation">

    <nav class="collapse -bg-gold navbar-collapse" id="js-lachitus-collapse">
      <ul class="nav h-text-md-center nav__main text-uppercase">
        <li><a class="nav" href="/products?type=collections">New Collections</a></li>
        <li><a class="nav" href="/products?type=clothing">Clothing</a></li>
        <li><a class="nav" href="/products?type=handbags">Handbags</a></li>
        <li><a class="nav" href="/products?type=shoes">Shoes</a></li>
        <li><a class="nav" href="/products?type=jewelry">Jewelry</a></li>
        <li><a class="nav" href="/products?type=accessories">Accessories</a></li>
      </ul>
    </nav>

  </div>
</section>
<section class="wrap-content section-about">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag("lachitus-aboutus.jpg", class: "img-responsive", alt: "Lachitus fashion") %>
      </div>
      <div class="col-sm-6">
        <div class="text-center headspacer-small spacer-medium">
          <p class="head-info spacer-xsmall">Modern fashion with high value and inexpensive collection</p>
          <p class="head-info spacer-xsmall">Eye - Catching Individualized</p>
          <p class="head-info">Where you <strong>express</strong> your aesthetic self</p>
        </div>
        <div class="text-center headspacer-small spacer-medium">
          <p class="head-info">A real voice for the astist, the outcast, the dreamer, the person you want tobe</p>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="wrap-content section-contact  text-center">
  <div class="container">
    <div class="row">
      <h2 class="headspacer-small spacer-medium">Contact Us</h2>
      <div class="col-sm-6">

        <div class="spacer-xlarge">

          <div class="spacer-medium">
            <p class="detail spacer-xsmall">Address:</p>
            <p class="head-info">745 East Valley Blvd PMB176 San Gabriel CA 91746</p>
          </div>
          <div class="spacer-medium">
            <p class="detail spacer-xsmall">Email:</p>
            <a  class="head-info spacer-medium" href="mailto:info@lachitus.com" target="_top">info@lachitus.com</a>
          </div>
          <div class="spacer-medium">
            <p class="detail spacer-xsmall">Phone:</p>
            <p class="head-info">+1 425 319 13 41</p>
          </div>
        </div>

      </div> <!-- col-sm-6 -->

      <div class="col-sm-6">
        <%= image_tag("lachitus-contact.jpg", class: "img-responsive", alt: "Lachitus fashion") %>
      </div> <!-- col-sm-6 -->
    </div>
    <div class="profile-social -bg-gold text-center headspacer-medium spacer-medium">

      <ul class="nav navbar-nav social">
        <li>
          <a class="ripple-centered" href="https://www.facebook.com" target="_blank"><i class="fa fa-3x fa-facebook"></i></a>
        </li>
        <li>
          <a class="ripple-centered" href="https://twitter.com/" target="_blank"><i class="fa fa-3x fa-twitter"></i></a>
        </li>
        <li>
          <a class="ripple-centered" href="https://www.linkedin.com/" target="_blank"><i class="fa fa-3x fa-linkedin"></i></a>
        </li>
        <li>
          <a class="ripple-centered" href="https://plus.google.com" target="_blank"><i class="fa fa-3x fa-google-plus"></i></a>
        </li>
        <li>
          <a class="ripple-centered" href="https://www.instagram.com/" target="_blank"><i class="fa fa-3x fa-instagram"></i></a>
        </li>
      </ul>

    </div> <!-- /.profile-social -->
  </div>
</section>

<section>
  <ul class="nav nav-collection">
    <li class="grid-box -bg-gold animated">
      <figure class="portfolio-figure">
        <%= image_tag("lachitus-clothing.jpg", class: "img-responsive", alt: "lachitus-fashion") %>
        <figcaption class="portfolio-caption">
          <div class="portfolio-caption-inner">
            <h3 class="portfolio-title text-center">
              Clothing
            </h3>
          </div>
        </figcaption>
      </figure>
    </li>
    <li class="grid-box -bg-gold animated">
      <figure class="portfolio-figure">
        <%= image_tag("lachitus-handbag.jpg", class: "img-responsive", alt: "lachitus-fashion") %>
        <figcaption class="portfolio-caption">
          <div class="portfolio-caption-inner">
            <h3 class="portfolio-title text-center">
              Handbag
            </h3>
          </div>
        </figcaption>
      </figure>
    </li>
    <li class="grid-box -bg-gold animated">
      <figure class="portfolio-figure">
        <%= image_tag("lachitus-shoe.jpg", class: "img-responsive", alt: "lachitus-fashion") %>
        <figcaption class="portfolio-caption">
          <div class="portfolio-caption-inner">
            <h3 class="portfolio-title text-center">
              Shoes
            </h3>
          </div>
        </figcaption>
      </figure>
    </li>
    <li class="grid-box -bg-gold animated">
      <figure class="portfolio-figure">
        <%= image_tag("lachitus-jewelry.jpg", class: "img-responsive", alt: "lachitus-fashion") %>
        <figcaption class="portfolio-caption">
          <div class="portfolio-caption-inner">
            <h3 class="portfolio-title text-center">
              Jewelry
            </h3>
          </div>
        </figcaption>
      </figure>
    </li>
    <li class="grid-box -bg-gold animated">
      <figure class="portfolio-figure">
        <%= image_tag("lachitus-accessories.jpg", class: "img-responsive", alt: "lachitus-fashion") %>
        <figcaption class="portfolio-caption">
          <div class="portfolio-caption-inner">
            <h3 class="portfolio-title text-center">
              Accessories
            </h3>
          </div>
        </figcaption>
      </figure>
    </li>
  </ul>
</section>

<section class="wrap-content section-charity text-center">
  <div class="container">
    <h2 class="headspacer-small spacer-medium">Lachitus Charity</h2>

    <h4><big><em><b>Lachitus</b></em> is also a philanthropic orgnaization helping those facing dounting circumstances.</big></h4>
    <h4><big>Financial resources from <em><b>Lachitus</b></em> products and partners are directed back to communicaties every year since 2015.</big></h4>

    <div class="row text-center">
      <div class="col-sm-6 headspacer-medium">
        <%= image_tag("lachitus-charity1.jpg", class: "img-responsive", alt: "Lachitus fashion charity") %>
      </div>
      <div class="col-sm-6 headspacer-medium">
        <%= image_tag("lachitus-charity2.jpg", class: "img-responsive", alt: "Lachitus fashion charity") %>
      </div>
    </div>
  </div>
</section>

app/views/pages/product-detail.html.erb
<section>
  <div class="container-fluid h-space-in-all-large">
    <div class="row">
      <div class="col-sm-12 col-md-offset-1 col-md-5 h-space-in-all-xsmall">
        <%= image_tag("lachitus-product1.jpg", class: "product img-responsive center-block", alt: "Lachitus fashion") %>
      </div>
      <div class="col-sm-12 col-md-5">
        <h3>Product Name</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
          incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
          exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
          dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
          Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <div class="row">
          <div class="col-xs-12 col-sm-8">
            <div class="btn-group" role="group" aria-label="...">
              <button type="button" class="btn btn-default">S</button>
              <button type="button" class="btn btn-default">M</button>
              <button type="button" class="btn btn-default">L</button>
              <button type="button" class="btn btn-default">XL</button>
            </div>
          </div>

          <div class="col-xs-4">
            <a href="/size-guide" target="_blank" class="btn btn-default btn-block">Size guide</a>
            <button class="btn btn--primary btn-block">Add to card</button>
          </div>

          <div class="col-xs-12 col-sm-4">
            <h4>Can I HELP YOU?</h4>
            <p>Telephone</p>
            <p>0123456789</p>

            <p>Email</p>
            <!-- <a href="/send-mail" class="btn btn--primary btn-block" target="_blank">SEND</a> -->

            <h4>Social Media</h4>
            <p>Facebook</p>
            <p>Instagram</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/send-mail.html.erb
<section>
  <div class="container h-space-in-all-large">


    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
        <h3>CUSTOMER SERVICE</h3>
        <h3>ONLINE SALES CONTACT FORM</h3>

        <div class="form-box headspacer-in-medium">
          <%= form_for(:mailer, class: "form") do |f| %>
            <div class="field form-group">
              <%= f.label :email, class: 'form-box__label' %><br />
              <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'email@lachitus.com' %>
            </div>

            <div class="field form-group">
              <%= f.label :message, class: 'form-box__label' %><br />
              <%= f.text_area :message, rows: "10",autocomplete: "off", class: 'none-resize form-control', placeholder: 'What I can help?' %>
            </div>

            <div class="actions">
              <%= f.submit "Send Mail", class: 'btn btn-default btn--primary btn-block form-box__button' %>
            </div>
          <% end %>
        </div>

      </div> <!-- /.col -->
    </div> <!-- /.row -->

  </div>
</section>

app/views/products/show.html.erb
<!-- <h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p> -->


<section>
  <div class="container-fluid h-space-in-all-large">
    <div class="row">
      <div class="col-sm-12 col-md-offset-1 col-md-5 h-space-in-all-xsmall">
        <%= image_tag @product.thumbnail_img.url(:medium), class: "product img-responsive center-block", alt: "Lachitus fashion" %>
      </div>
      <div class="col-sm-12 col-md-5">
        <h3><%= @product.title %></h3>
        <p><%= @product.description %></p>
        <div class="row">
          <div class="col-xs-12 col-sm-8">
            <div class="btn-group" role="group" aria-label="...">
              <button type="button" class="btn btn-default">S</button>
              <button type="button" class="btn btn-default">M</button>
              <button type="button" class="btn btn-default">L</button>
              <button type="button" class="btn btn-default">XL</button>
            </div>
          </div>

          <div class="col-xs-4">
            <a href="/size-guide" target="_blank" class="btn btn-default btn-block">Size guide</a>
            <%=link_to "", class: "btn btn--primary btn-block", data: {target: @cart_action, addUrl: add_to_cart_path(@product), removeUrl: remove_from_cart_path(@product)} do%>
              <i class="fi-shopping-cart"></i>
              <span><%=@cart_action%></span> Cart
            <%end%>
          </div>

          <div class="col-xs-12 col-sm-4">
            <h4>Can I HELP YOU?</h4>
            <p>Telephone</p>
            <p>0123456789</p>

            <p>Email</p>
            <!-- <a href="/send-mail" class="btn btn--primary btn-block" target="_blank">SEND</a> -->

            <h4>Social Media</h4>
            <p>Facebook</p>
            <p>Instagram</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
   <div class="field form-group">
    <%= f.label :address, class: 'form-box__label' %><br>
    <%= f.text_field :address, class: 'form-control form-box__input'%>
  </div>
  <div class="field">
    <%= f.label :user_name, class: 'form-box__label' %><br>
    <%= f.text_field :user_name, class: 'form-control form-box__input'%>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Update", class: 'btn btn-default btn--primary form-box__button' %>
  </div>
<% end %>